name: dpd-vertx-service docker
on: 
  push: 
    branches: 
      - 'master'
jobs:
  build-and-publish:
    name: build and publish
    runs-on: ubuntu-latest

    steps:
      - name: check out the source code
        uses: actions/checkout@v2
      - name: set up java 
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt' 
          java-version: '11'
      - name: install maven
        run: apt update && apt install maven
      - name: build project
        run: mvn clean package
      - name: build docker image
        run: docker build -t weifang993/drug-vertx-service .
      - name: docker login
        # run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}        
      - name: docker push
        run: docker push weifang993/drug-vertx-service